### ISSUE TITLE
Bullets - Spacing on Chrome vs Other Browsers

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/droplets#29]
It looks like bullets are being rendered with extra spacing inside of Chrome right now. They appear fine in Safari and Firefox.

Attached is a screenshot of Chrome.

![pasted image at 2017_01_23 13_06](https://cloud.githubusercontent.com/assets/237349/22225261/634a734c-e187-11e6-9bcf-8ca5d718b6b0.png)

**Comment by owlboy** [comment]
[d2l-bullets-code.txt](https://github.com/oel-mediateam/droplets/files/725112/d2l-bullets-code.txt)

**Comment by Lin87** [comment]
User error. 🤣
